### ISSUE TITLE
Using Camellia 1.0 with Chromium Edge would cause the option page to display incompletely

### ISSUE THREAD

**Issue by idlist** [camellia-app/camellia#46] opened 2021-08-11 06:50 UTC
When searching for a bookmark manager in GitHub, I was quite impressed by how Camellia fits my needs and gave it a try. The new tab looks pretty good with simple interface and clear listing of my tons of bookmarks

The only flaw I found is that when I want to configure the extension, the option window cannot display completely in my Edge browser. The most bottom of the option list I can reach is here (as the screenshot shown below), and the "save" button is beyond the option frame.

![image](https://user-images.githubusercontent.com/29368226/128980605-9abaf421-07e2-4de8-97d9-01925350f657.png)

Currently I used `F12` to expand the option window to reach the "save" button, so it does not cause much difficulty 
for me, but it would be better if this could be fixed (or does not appear again in Camellia 2.0).

Thanks.

**Comment by flaksp** [comment] 2023-02-17 21:33
I close the issue because it was related to old Camellia. [New Camellia officially announced](https://github.com/camellia-app/camellia/discussions/407) and will be shipped soon, so the issue is irrelevant now.

**Closed by flaksp** 2023-02-17 21:33 UTC
Labels: bug
