### ISSUE TITLE
Request: option for toggle on the folders open/close by default

### ISSUE THREAD

**Issue by quodran** [camellia-app/camellia#334] opened 2022-12-09 15:53 UTC
It would be great is there was an option to choose if a folder should be opened or closed, or by default all opened or all closed.

**Comment by flaksp** [comment] 2022-12-10 16:24
There will be major redesign of the app that will introduce new folder design like on the screen shot, so your feature request won't be applicable here:

<img width="833" alt="Screenshot 2022-12-10 at 19 12 53" src="https://user-images.githubusercontent.com/12474739/206864471-a8974090-7122-43ac-93aa-d2e7d969cbc6.png">

However, if the reason you are asking for the feature is you want to group some bookmarks and have quick access to them (without always clicking a folder to open it), then there is a planned feature that will allow you to convert a folder into a category (see #31 for details).

**Comment by flaksp** [comment] 2023-02-17 21:32
I close the issue because it was related to old Camellia. [New Camellia officially announced](https://github.com/camellia-app/camellia/discussions/407) and will be shipped soon, so the issue is irrelevant now.

**Closed by flaksp** 2023-02-17 21:32 UTC
Labels: enhancement
